[tool.black]
line-length = 100
target-version = ['py310']

[tool.pylint.format]
max-line-length = 100

[tool.pylint."MESSAGES CONTROL"]
disable = ["too-many-instance-attributes"]

[tool.pylint."BASIC"]
ignore-paths=["src/", "mobile_app/"]
