[tool.black]
line-length = 100
target-version = ['py310']
exclude = '''
/(
    .git
  | .github
  | src
)/
'''

[tool.isort]
profile = "black"

[tool.pylint.format]
max-line-length = 100

[tool.pylint."MESSAGES CONTROL"]
disable = ["too-many-instance-attributes", "fixme", "too-many-locals"]

[tool.pylint."BASIC"]
ignore-paths=["src/", "mobile_app/"]
