name: Run Pytest

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Download and unpack test data
        run: |
          cd tests/
          ./download_test_data.sh
          tar -xzf data.tar.gz
          cd ..

      - name: Set PYTHONPATH environment variable
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run Pytest
        run: |
          pytest --disable-warnings tests/

      - name: Uninstall torch and onnx
        run: |
          pip uninstall -y torch torchvision onnx onnxruntime

      - name: Set test environment variables
        run: |
          echo "WITHOUT_TORCH=1" >> $GITHUB_ENV
          echo "WITHOUT_ONNX=1" >> $GITHUB_ENV

      - name: Run Pytest for the module loading
        run: |
          pytest --disable-warnings tests/test_module_loading.py
